# Generated by Django 5.0.14 on 2025-09-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('event_description', models.TextField(blank=True, null=True, verbose_name='事件描述')),
                ('style_preference', models.CharField(choices=[('formal', '正式'), ('casual', '休闲'), ('humorous', '幽默'), ('inspirational', '励志'), ('informative', '信息性')], max_length=20, verbose_name='风格偏好')),
                ('language', models.CharField(choices=[('zh', '中文'), ('en', 'English'), ('ja', '日本語'), ('ko', '한국어')], default='zh', max_length=10, verbose_name='语言')),
                ('audience_type', models.CharField(choices=[('general', '大众'), ('youth', '青年'), ('professionals', '专业人士'), ('parents', '家长'), ('students', '学生')], default='general', max_length=20, verbose_name='受众类型')),
                ('audience_description', models.TextField(blank=True, null=True, verbose_name='受众描述')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='附加说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='生成内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_contents', to='content_generator.contentgenerationrequest')),
            ],
        ),
    ]
