# Generated by Django 5.0.14 on 2025-09-17 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcontent',
            name='request',
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('summary', models.TextField(verbose_name='总结内容')),
                ('work_evaluation', models.TextField(blank=True, null=True, verbose_name='工作评估')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '日总结',
                'verbose_name_plural': '日总结',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('content', models.TextField(verbose_name='事件内容')),
                ('mood', models.CharField(choices=[('😄', '开心'), ('😢', '悲伤'), ('😠', '愤怒'), ('😲', '惊讶'), ('😴', '困倦'), ('😍', '兴奋'), ('🤔', '思考'), ('😎', '酷')], default='😄', max_length=2, verbose_name='心情')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '事件记录',
                'verbose_name_plural': '事件记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='建议内容')),
                ('advice_type', models.CharField(choices=[('task', '任务建议'), ('event', '事件分享'), ('summary', '总结建议')], max_length=10, verbose_name='建议类型')),
                ('related_id', models.IntegerField(verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'LLM建议',
                'verbose_name_plural': 'LLM建议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('willingness', models.CharField(choices=[('😭', '很不情愿'), ('😕', '不太情愿'), ('😐', '一般'), ('🙂', '比较愿意'), ('😄', '很愿意')], default='😐', max_length=2, verbose_name='意愿度')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContentGenerationRequest',
        ),
        migrations.DeleteModel(
            name='GeneratedContent',
        ),
    ]
