# Generated by Django 5.0.14 on 2025-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generator', '0002_remove_generatedcontent_request_dailysummary_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '♛♛♛'), ('medium', '♛♛'), ('low', '♛')], default='medium', max_length=10, verbose_name='优先级'),
        ),
    ]
