# Generated by Django 5.2.6 on 2025-09-17 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='支持 JPG, JPEG, PNG, GIF 格式', null=True, upload_to='uploads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('event_description', models.TextField(blank=True, help_text='描述要陈述的事件内容', max_length=1000, null=True)),
                ('style', models.CharField(choices=[('casual', '轻松随意'), ('formal', '正式严肃'), ('humorous', '幽默风趣'), ('emotional', '深情感人'), ('inspirational', '励志向上'), ('professional', '专业商务'), ('trendy', '时尚潮流'), ('literary', '文艺清新'), ('minimalist', '简约风格'), ('dramatic', '戏剧化')], help_text='选择想要的内容风格', max_length=20)),
                ('language', models.CharField(choices=[('zh-cn', '中文简体'), ('zh-tw', '中文繁體'), ('en', 'English'), ('ja', '日本語'), ('ko', '한국어'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português'), ('ru', 'Русский')], default='zh-cn', help_text='选择生成内容的语言', max_length=10)),
                ('audience_type', models.CharField(help_text='目标受众类型，如：朋友、同事、粉丝等', max_length=100)),
                ('audience_description', models.TextField(help_text='详细描述你的受众特征', max_length=500)),
                ('additional_notes', models.TextField(blank=True, help_text='其他补充说明', max_length=500, null=True)),
                ('generated_content', models.JSONField(blank=True, help_text='存储生成的5条文案内容', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '内容生成请求',
                'verbose_name_plural': '内容生成请求',
                'ordering': ['-created_at'],
            },
        ),
    ]
